name: ${project.name}
main: dev.alexzvn.petstats.FancyPetStats
version: ${project.version}
api-version: 1.16

author: Alexzvn
website: https://github.com/alexzvn

load: STARTUP
depend:
  - MCPets
  - MMOCore

softdepend:
  - LuckPerms